CREATE TABLE `BRAND`(
    `BRAND_ID` INT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `BRAND_NAME` VARCHAR(120) NOT NULL
);

CREATE TABLE `CATEGORY`(
    `CAT_ID` INT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `CAT_NAME` VARCHAR(120) NOT NULL
);

CREATE TABLE `PRODUCT`(
    `P_ID` INT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `P_NAME` VARCHAR(120) NOT NULL,
    `P_PHOTO` VARCHAR(120) NOT NULL,
    `P_PRICE` INT(20) NOT NULL,
    `P_QTY` INT(20) NOT NULL,
    `P_DESC` VARCHAR(1000) NOT NULL,
    `BRAND_ID` INT(20) NOT NULL,
    `CAT_ID` INT(20) NOT NULL,
    `INPUT_BY_ID` INT(20) NOT NULL,
    `INPUT_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `EDITED_BY_ID` INT(20) NOT NULL,
    `EDIT_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `S_ID` INT(20) NOT NULL
);


CREATE TABLE `SUPPLIER` (
    `S_ID` INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    `S_NAME` VARCHAR(120) NOT NULL,
    `S_EMAIL` VARCHAR(120) NOT NULL,
    `S_ADDRESS` VARCHAR(225) NOT NULL,
    `S_PHONE_NUMBER` VARCHAR (20) NOT NULL,
    `S_WA_NUMBER` VARCHAR (20) NOT NULL
);

CREATE TABLE `ADMIN`(
    `ADM_ID` INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT ,
    `ADM_PHOTO` VARCHAR(120) NOT NULL,
    `ADM_FNAME` VARCHAR(120) NOT NULL,
    `ADM_LNAME` VARCHAR(120) NOT NULL,
    `ADM_UNAME` VARCHAR(120) NOT NULL,
    `ADM_EMAIL` VARCHAR(120) NOT NULL,
    `ADM_PHONE_NUMBER` VARCHAR(120) NOT NULL,
    `ADM_WA_NUMBER` VARCHAR(120) NOT NULL,
    `ADM_PASSWORD` VARCHAR(120) NOT NULL,
    `ADM_CREATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `ADM_UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `USER`(
    `U_ID` INT(20) PRIMARY  KEY NOT NULL AUTO_INCREMENT,
    `U_FNAME` VARCHAR(120) NOT NULL,
    `U_LNAME` VARCHAR(120) NOT NULL,
    `U_EMAIL` VARCHAR(120) NOT NULL,
    `U_PNUM` VARCHAR(120) NOT NULL,
    `U_PPCODE` INT(5) NOT NULL,
    `U_PROVINCE` INT(2) NOT NULL,
    `U_CITY` INT(4) NOT NULL,
    `U_DIST` INT(7) NOT NULL,
    `U_SUBDIST` VARCHAR(10) NOT NULL,
    `U_PASS` VARCHAR(120) NOT NULL,
    `U_CREATE_TIME` TIMESTAMP 
);

CREATE TABLE `CART`(
    `CART_ID` INT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    `U_ID` INT(20) NOT NULL,
    `CART_STATUS` VARCHAR(100) NOT NULL
);

CREATE TABLE `CART_CONTAINER`(
    `CART_ID` INT(20) NOT NULL,
    `P_ID` INT(20) NOT NULL,
    `P_B_QTY` INT(20) NOT NULL,
    `P_B_SUM` INT(20) NOT NULL
);

ALTER TABLE PRODUCT
ADD FOREIGN KEY (BRAND_ID) REFERENCES BRAND(BRAND_ID),
ADD FOREIGN KEY (CAT_ID) REFERENCES CATEGORY(CAT_ID),
ADD FOREIGN KEY (INPUT_BY_ID) REFERENCES admin(ADM_ID),
ADD FOREIGN KEY (EDITED_BY_ID) REFERENCES admin(ADM_ID)
ADD FOREIGN KEY (s_ID) REFERENCES SUPPLIER(S_ID);

ALTER TABLE CART
ADD FOREIGN KEY (U_ID) REFERENCES USER(U_ID);

ALTER TABLE CART_CONTAINER
ADD FOREIGN KEY (CART_ID) REFERENCES CART(CART_ID),
ADD FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID);